[package]
build = "build.rs"
name = "rusty_gl"
version = "0.1.0"
edition = "2024"

[build-dependencies]
bindgen = "0.72.0"
cc = "1.2.33"

[dependencies]
assimp = "0.3.1"
memmap2 = "0.9.7"
ndarray = "0.16.1"
ndarray-linalg = { version = "0.17.0", features = ["openblas"] }

